# Mission 1

![](https://i.imgur.com/Ax3pp2A.png)


Create a "fruit" dataframe that reflects the above example **using a list** data structure

[This resource could help you](https://datatofish.com/list-to-dataframe/).

In [16]:
import pandas as pd
df = pd.DataFrame([[30,21]], columns=["Apple","Bananas"])
df

   Apple  Bananas
0     30       21

# Mission 2

Create a "fruit_vendors" dataframe that reflects the below example **using a dictionary** data structure

![](https://i.imgur.com/CHPn7ZF.png)

[This resource could help you.](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.from_dict.html)

In [11]:
fruit_vendors = pd.DataFrame({
    'Apples': {'2017 Sales': 35, '2018 Sales': 41},
    'Bananas': {'2017 Sales': 21, '2018 Sales': 34},
})
fruit_vendors

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

# Mission 3

Use a loop to display the values from each column in the dataframe from mission 2.

[This resource could help you](https://www.w3schools.com/python/pandas/ref_df_items.asp)

In [21]:
for colonne in fruit_vendors.columns:
  print(colonne, fruit_vendors[colonne].values)

Apples [35 41]
Bananas [21 34]

# Mission 4

Delete the first row of the dataframe from mission 2

[This resource could help you.](https://sparkbyexamples.com/pandas/pandas-drop-first-row-of-dataframe/#google_vignette)

In [22]:
df2 = fruit_vendors.drop("2017 Sales")


"""ou"""

df3 = fruit_vendors.drop(fruit_vendors.index[0])

df2 , df3

(            Apples  Bananas
 2018 Sales      41       34,
             Apples  Bananas
 2018 Sales      41       34)

# Mission 5

Delete the first column from the dataframe from mission 2.

In [28]:
df4 = fruit_vendors.drop(columns=fruit_vendors.columns[0])

df4

            Bananas
2017 Sales       21
2018 Sales       34