# Mission 1

Display the following information [for this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user).
- The last 5 rows
- The first 5 rows
- The type of each column

Note : start coding something by typing `pd.read_csv()` and explore the different options available, especially the `sep` parameter.

In [6]:
import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/u.user", sep="|")
df.tail(5)

       1  24  M     technician  85711
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

In [7]:
df.head()

   1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

In [8]:
df.dtypes

1              int64
24             int64
M             object
technician    object
85711         object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 942 entries, 0 to 941
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   1           942 non-null    int64
 1   24          942 non-null    int64
 2   M           942 non-null    object
 3   technician  942 non-null    object
 4   85711       942 non-null    object
dtypes: int64(2), object(3)
memory usage: 36.9+ KB

# Mission 2

Display the first 10 rows [in the following file](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv)

In [10]:
df1 = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/drinks.csv", sep=",")
df1.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,Asia
1,Albania,89,132,54,4.9,Europe
2,Algeria,25,0,14,0.7,Africa
3,Andorra,245,138,312,12.4,Europe
4,Angola,217,57,45,5.9,Africa
5,Antigua & Barbuda,102,128,45,4.9,North America
6,Argentina,193,25,221,8.3,South America
7,Armenia,21,179,11,3.8,Europe
8,Australia,261,72,212,10.4,Oceania
9,Austria,279,75,191,9.7,Europe

Set the "country" column as the index for the dataframe, using `set_index` method.

In [ ]:
df1.set_index("country", inplace=True)

In [12]:
df1

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Afghanistan,0,0,0,0.0,Asia
Albania,89,132,54,4.9,Europe
Algeria,25,0,14,0.7,Africa
Andorra,245,138,312,12.4,Europe
Angola,217,57,45,5.9,Africa
...,...,...,...,...,...
Venezuela,333,100,3,7.7,South America
Vietnam,111,2,1,2.0,Asia
Yemen,6,0,0,0.1,Asia
Zambia,32,19,4,2.5,Africa
Zimbabwe,64,18,4,4.7,Africa

# Mission 3

Access the values of the row for **Zimbabwe** (use the index value)

In [20]:
df1.iloc[-1,:]

beer_servings                       64
spirit_servings                     18
wine_servings                        4
total_litres_of_pure_alcohol       4.7
continent                       Africa
Name: Zimbabwe, dtype: object

In [22]:
df1[df1.index =='Zimbabwe']

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
country,,,,,
Zimbabwe,64,18,4,4.7,Africa

# Mision 4

Display only the "continent" column value for the country **Zimbabwe**.

In [25]:
df1.loc["Zimbabwe","continent"]

'Africa'

# Mission 5

Rename the columns [of this dataset](https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv), try using the following 2 different methods to achieve this:
- Setting column names directly when reading the file
- Editing after creating the dataframe ([This resource could be useful](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html))

In [29]:
df2 = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv", sep=",")
df2 = df2.rename(columns={"City": "Ville", "Colors Reported": "Couleurs","Shape Reported": "Forme", "State": "État", "Time": "Date"})
df2

                      Ville Couleurs     Forme État              Date
0                    Ithaca      NaN  TRIANGLE   NY    6/1/1930 22:00
1               Willingboro      NaN     OTHER   NJ   6/30/1930 20:00
2                   Holyoke      NaN      OVAL   CO   2/15/1931 14:00
3                   Abilene      NaN      DISK   KS    6/1/1931 13:00
4      New York Worlds Fair      NaN     LIGHT   NY   4/18/1933 19:00
...                     ...      ...       ...  ...               ...
18236            Grant Park      NaN  TRIANGLE   IL  12/31/2000 23:00
18237           Spirit Lake      NaN      DISK   IA  12/31/2000 23:00
18238           Eagle River      NaN       NaN   WI  12/31/2000 23:45
18239           Eagle River      RED     LIGHT   WI  12/31/2000 23:45
18240                  Ybor      NaN      OVAL   FL  12/31/2000 23:59

[18241 rows x 5 columns]

In [30]:
head = ["Ville","Couleurs","Forme","État","Date"]
df3 = pd.read_csv("https://raw.githubusercontent.com/justmarkham/pandas-videos/master/data/ufo.csv",names=head,header=0, sep=",")
df3

                      Ville Couleurs     Forme État              Date
0                    Ithaca      NaN  TRIANGLE   NY    6/1/1930 22:00
1               Willingboro      NaN     OTHER   NJ   6/30/1930 20:00
2                   Holyoke      NaN      OVAL   CO   2/15/1931 14:00
3                   Abilene      NaN      DISK   KS    6/1/1931 13:00
4      New York Worlds Fair      NaN     LIGHT   NY   4/18/1933 19:00
...                     ...      ...       ...  ...               ...
18236            Grant Park      NaN  TRIANGLE   IL  12/31/2000 23:00
18237           Spirit Lake      NaN      DISK   IA  12/31/2000 23:00
18238           Eagle River      NaN       NaN   WI  12/31/2000 23:45
18239           Eagle River      RED     LIGHT   WI  12/31/2000 23:45
18240                  Ybor      NaN      OVAL   FL  12/31/2000 23:59

[18241 rows x 5 columns]

# Mission 6

Select the first 3 rows and all the columns of the dataframe using iloc

In [31]:
df3.iloc[:3]

         Ville Couleurs     Forme État             Date
0       Ithaca      NaN  TRIANGLE   NY   6/1/1930 22:00
1  Willingboro      NaN     OTHER   NJ  6/30/1930 20:00
2      Holyoke      NaN      OVAL   CO  2/15/1931 14:00

# Mission 7

Achieve the same result as in mission 6 by using loc

In [34]:
df3.loc[0:2,head]

         Ville Couleurs     Forme État             Date
0       Ithaca      NaN  TRIANGLE   NY   6/1/1930 22:00
1  Willingboro      NaN     OTHER   NJ  6/30/1930 20:00
2      Holyoke      NaN      OVAL   CO  2/15/1931 14:00